apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      readOnly: false
      fsType: ext4
      secretRef:
        name: kvcreds
      options:
        region: ""
        cloudname: ""
        keyvaultname: ""
        keyvaultobjectname: ""
        keyvaultobjecttype: ""
        resourcegroup: ""
        subscriptionid: ""
        tenantid: ""
